//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CepNot.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notes
    {
        public int NoteID { get; set; }
        public string Report { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Type { get; set; }
        public Nullable<bool> Status { get; set; }
        public int UserId { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
